backend:
  name: github
  repo: florakija/learnbitcoin-club
  branch: main
  auth_type: pkce
  app_id: "Ov23liNmY7K0F7QspAVo"

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Typ", name: "type", widget: "select", options: ["article", "video", "document"], default: "article" }
      - { label: "Kurzbeschreibung", name: "excerpt", widget: "string" }
      - { label: "YouTube Video ID (optional)", name: "youtube_id", widget: "string", required: false }
      - { label: "Beitragsbild", name: "image", widget: "image", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }
